import torch
import json
import time
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
)

#import os, torch, wandb
#from datasets import load_dataset
from trl import setup_chat_format

MODEL_NAME = 'llama-3-70b-populate-ontology' #
BASE_DIRECTORY = '/home2020/home/icube/fghazoua/TetraProject'

model_directory = f'{BASE_DIRECTORY}/{MODEL_NAME}'

torch_dtype = torch.float16
# attn_implementation = "eager" 
attn_implementation = "flash_attention_2"

# QLoRA config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch_dtype,
    bnb_4bit_use_double_quant=True,
)

print("Process started....")
start_time = time.time()
# Load model
model = AutoModelForCausalLM.from_pretrained(
    model_directory,
    quantization_config=bnb_config,
    device_map="auto",
    attn_implementation=attn_implementation
)


# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_directory)

if hasattr(tokenizer, "chat_template") and tokenizer.chat_template is not None:
    tokenizer.chat_template = None  # Reset the chat template

model, tokenizer = setup_chat_format(model, tokenizer)

messages = [
    {
        "role": "system",
        "content": "Translate the user text into an TTL graph based on the TetraOnto ontology."
    },
    {
        "role": "user",
        "content": """The restoration project involves the creation of a fish pass at Brisach on the Rhine. This initiative is designed to improve the longitudinal continuity of the Rhine river, which is located in the Haut-Rhin department of France, in the commune of Brisach. The project owner is CERGA SA. This measure was made necessary by the construction of a micro-hydropower plant in 2008, a Franco-German infrastructure (EDF and EnBW) using a 5.7-meter head generated by an agricultural dam built between 1962 and 1965.
The works involved the creation of a fish pass with four entrances, a “classic” pass to facilitate upstream migration, and an downstream system with two structures installed on either side of the gate to enable fish to bypass the turbine. In addition, a trapping system has been installed for scientific fish monitoring.
Biological monitoring is carried out to assess the effectiveness of the restoration, although no hydromorphological monitoring has been undertaken. The project is expected to be completed by 2012 and has a total cost about 87,510 €."""
    }
]

prompt = tokenizer.apply_chat_template(messages, tokenize=False, 
                                       add_generation_prompt=True)

inputs = tokenizer(prompt, return_tensors='pt', padding=True, 
                   truncation=True).to("cuda")

outputs = model.generate(**inputs, max_length=16200, 
                         num_return_sequences=1)

text = tokenizer.decode(outputs[0], skip_special_tokens=True)

print(text.split("assistant")[1])

end_time = time.time()
execution_time = end_time - start_time
minutes, seconds = divmod(execution_time, 60)
formatted_time = f"{int(minutes)} minutes and {seconds:.2f} seconds"
print(f"Execution time for model '{MODEL_NAME}' is: {formatted_time}")
